spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**,/api/user/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**
        - id: venue-service
          uri: lb://venue-service
          predicates:
            - Path=/api/venue/**
        - id: info-service
          uri: lb://info-service
          predicates:
            - Path=/api/info/**
        - id: stat-service
          uri: lb://stat-service
          predicates:
            - Path=/api/stat/**
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
      config:
        server-addr: localhost:8848
        namespace: public
        file-extension: yaml

server:
  port: 8080
