spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**,/api/user/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**
        - id: venue-service
          uri: lb://venue-service
          predicates:
            - Path=/api/venue/**
        - id: info-service
          uri: lb://info-service
          predicates:
            - Path=/api/info/**
        - id: stat-service
          uri: lb://stat-service
          predicates:
            - Path=/api/stat/**
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
      config:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP  # 配置分组（默认DEFAULT_GROUP）
        name: gateway  # 配置文件名（默认与应用名相同）
        file-extension: yml  # 配置文件格式（yml 或 properties）
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}  # 核心配置，指定导入Nacos的配置源
server:
  port: 8080
